config/routes.rb
Rails.application.routes.draw do
  
  resources :pages
    resources :groups do
        collection do
            post 'join'
            post 'unjoin'
        end
    end
    get 'dashboard/index'
    #get 'posts/checkout'
    get 'notes/donate'
    get 'notes/accept'
    get 'home/index'
    get 'home/aboutus'
    get 'home/contact'
    get 'home/faq'
    get 'home/map'
    get 'home/privacy'
    get 'home/tos'
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :posts do
      resources :post_applications, only: [:create, :destroy]

      member do 
        patch 'accept_applicant'
        patch 'unaccept_applicant'
        get 'checkout'
        get 'accept'
        # post 'pay_teenager'
      end
    end

    get 'posts/checkout'
    get 'delete_resume' => 'pages#delete_resume'
    get 'delete_transcript' => 'pages#delete_transcript'



    root 'home#index'
    
    resource :profiles

    resources :notes
    get 'note/index'
    get 'like' => 'notes#like'
    get 'unlike' => 'notes#unlike'
    get 'dislike' => 'notes#dislike'
    get 'undislike' => 'notes#undislike'
    
    
    resources :notes do
        resources :comments
    end
    resources :users do
        resources :comments
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups_created = Group.all.select { |a| a.user_id == current_user.id }
    @memberships = Member.all.select { |a| a.user_id == current_user.id}.pluck(:group_id)
    @groups_joined = Group.all.select { |a| @memberships.include? a.id }
    @jobs = PostApplication.where({user_id: current_user.id , is_accepted: true})
    @pending = PostApplication.where({user_id: current_user.id , is_accepted: false})

    @notes = Note.all
  end


  def checkout
    @groups = Group.all
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<br>
<div class="row">
    <div class="col-12 text-center">
    
    <% if user_signed_in? %>
        <h2 style="margin-top:10vh">Welcome to your dashboard, <strong><%= current_user.page.name %></strong>.</h2>
        <h3>Current Balance: <strong>$<%= current_user.balance %></strong></h3>
    <% end %>
    </div>
</div>
<% if @groups_created.empty?%>
    <div class="col-12 text-center">
        <h1 style="margin-top:5vh;">Looks like your not hosting any group sessions :(</h1>
        <%= link_to 'Create study group', new_group_path, class: "btn btn-light dashbutton"%>

    </div>


<%else%>
    <h1>Groups you created:</h1>
    <br>
    <div class="table-responsive">
    <table class="table">
    <thead class="thead-dark">
        <th scope="col"><h6>Lead</h6></th>
        <th scope="col"><h6>Course</h6></th>
        <th scope="col"><h6>Description</h6></th>
        <th scope="col"><h6>Date</h6></th>
        <th scope="col"><h6>Time</h6></th>
        <th scope="col"><h6>Duration (hrs)</h6></th>
        <th scope="col"><h6>Location</h6></th>
        <th scope="col"><h6>Capacity</h6></th>
        <th scope="col"><h6>Expand</h6></th>
    </thead>

    <tbody>
        
        <% @groups_created.each do |group| %>
            <tr>
                <td><%= group.user.page.name %></td>
                <td><%= group.category %></td>
                <td><%= group.description %></td>
                <td><%= group.date %></td>
                <td><%= group.time.to_s(:time) %></td>
                <td><%= group.duration %></td>
                <td><%= group.location %></td>
                <td><%= group.capacity %></td>
                <td><%= link_to 'Show', group %>
                <%= link_to 'Edit', edit_group_path(group) %>
                <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
</div>
<%end %>





<br>
<br>

    <% if @groups_joined.empty?%>
    <div class="col-12 text-center">
        <h1 style="margin-top:5vh;">Looks like your not a member of any group sessions :(</h1>
        <%= link_to 'Explore more study groups', groups_path, class: "btn btn-light dashbutton"%>

    </div>

<%else%>


    <h1>Groups you joined:</h1>
    <div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <th scope="col"><h6>Lead</h6></th>
            <th scope="col"><h6>Course</h6></th>
            <th scope="col"><h6>Description</h6></th>
            <th scope="col"><h6>Date</h6></th>
            <th scope="col"><h6>Time</h6></th>
            <th scope="col"><h6>Duration (hrs)</h6></th>
            <th scope="col"><h6>Location</h6></th>
            <th scope="col"><h6>Capacity</h6></th>
            <th scope="col"><h6>Expand</h6></th>
        </thead>

        <tbody>
            <% @groups_joined.each do |group| %>
                <tr>
                    <td><%= group.user.page.name %></td>
                    <td><%= group.category %></td>
                    <td><%= group.description %></td>
                    <td><%= group.date %></td>
                    <td><%= group.time.to_s(:time) %></td>
                    <td><%= group.duration %></td>
                    <td><%= group.location %></td>
                    <td><%= group.capacity %></td>
                    <td><%= link_to 'Show', group %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    </div>
        <%= link_to 'Explore more study groups', groups_path, class:"btn btn-light dashbutton"%>

<%end %>

<br>
<br>
<% if current_user.notes.empty?%>
    <div class="col-12 text-center">
        <h1 style="margin-top:5vh;">Help our community grow by posting notes!</h1>
        <%= link_to 'Create Notes', new_note_path, class:"btn btn-light dashbutton"%>
    </div>
<% else %>
<h1>Your posted notes</h1>

<div  class="row" >
    <% current_user.notes.each do |note|%>
    <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
        <div class="card">

            <div class="card-body">
                <h4><%= note.course %> - <%= note.prof %></h4>
                <h2 class="title"><%= link_to note.title, note %></h2>

                <p class="card-text"><%= note.content %> </p>
                <% note.attachments.blobs.each do |document| %>
                    <p class="card-text">
                        <%= link_to document.filename, rails_blob_path(document, disposition: 'preview'), target: :_blank, :class => 'link_to_color' %>
                    </p>
                <% end %>
                <p class="card-text">By <%= link_to note.user.page.name, page_path(note.user.id), :class => 'link_to_color' %></p>


                <p>Likes: <%= note.cached_votes_score %>
                (<% if note.cached_votes_total == 0 %><%= note.cached_votes_up.to_f * 100 %>
                <% else %><%= (note.cached_votes_up.to_f/note.cached_votes_total.to_f * 100).round(2) %>
                <% end %>%)
                </p>
            </div>
            <div class="card-footer">
                <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(note.created_at)%> ago</small></p>

            </div>
        </div>
    </div>
    <% end %>
</div>
<%end %>

<br>
<br>
<div class="col-12 text-center" style="margin-top:5vh;">
<h1>Your liked notes</h1>
</div>
<div  class="row" >
    <% @notes.each do |note|%>
        <% if current_user.voted_up_on? note %>
        <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
            <div class="card">

                <div class="card-body">
                    <h4><%= note.course %> - <%= note.prof %></h4>
                    <h2 class="title"><%= link_to note.title, note %></h2>

                    <p class="card-text"><%= note.content %> </p>
                    <p class="card-text">By <%= link_to note.user.page.name, page_path(note.user.id), :class => 'link_to_color' %></p>

                    <p>Likes: <%= note.cached_votes_score %>
                    (<% if note.cached_votes_total == 0 %><%= note.cached_votes_up.to_f * 100 %>
                    <% else %><%= (note.cached_votes_up.to_f/note.cached_votes_total.to_f * 100).round(2) %>
                    <% end %>%)
                    </p>
                </div>
                <div class="card-footer">
                    <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(note.created_at)%> ago</small></p>

                </div>
            </div>
        </div>
        <% end %>
    <% end %>
</div>

<br>
<br>

<% if current_user.posts.empty? %>
<div class="col-12 text-center">
    <h1>Seems like you need a Buddy.  <%= link_to 'Create Job', '/posts/new' %><h1>
</div>
<% else %>
<div class="col-12 text-center">
    <h1>Your Jobs: </h1>
</div>

<%end %>

<div  class="row" >
    <% current_user.posts.each do |post|%>

        <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
            <div class="card">

                <div class="card-body">
                    
                    <h2 class="card-title title"><%= link_to post.title, post %></h2>

                    <p class="card-text"><%= post.content %></p>
                    <p class="card-text"><%= post.limit %></p>
                    <p class="card-text"><small class="text-muted"><%= post.user.email %></small></p>
                    
                </div>
                <div class="card-footer">
                    <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(post.created_at)%> ago</small></p>

                </div>
            </div>
        </div>
    <% end %>
</div>


<% if @jobs.empty? %>
    <div class="col-12 text-center dashtitle">
    <h1>You have no Job offers.  <%= link_to 'Apply', '/posts/' %><h1>
    </div>
<% else %>
    <div class="col-12 text-center dash-title">

    <h1>Your Jobs: </h1>
    </div>
<%end %>


<div  class="row" >
    <% @jobs.each do |app|%>
        <% post = app.post %>

        <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
            <div class="card">

                <div class="card-body">
                    
                    <h2 class="card-title title"><%= link_to post.title, post %></h2>

                    <p class="card-text"><%= post.content %></p>
                    <p class="card-text"><%= post.limit %></p>
                    <p class="card-text"><small class="text-muted"><%= post.user.email %></small></p>
                    
                </div>
                <div class="card-footer">
                    <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(post.created_at)%> ago</small></p>

                </div>
            </div>
        </div>
    <% end %>
</div>






<% if @pending.empty? %>
    <div class="col-12 text-center dashtitle">

    <h1>You have no pending applications. <%= link_to 'Apply', '/posts/' %><h1>
    </div>
<% else %>
    <div class="col-12 text-center dashtitle">

    <h1>Pending Applications:</h1>
    </div>
<%end %>
<div  class="row" >
    <% @pending.each do |app|%>
        <% post = app.post %>
        <% next if post.is_accepting_applicants == false %>
        <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
            <div class="card">

                <div class="card-body">
                    <h1><%= app.id %></h1>
                    <h2 class="card-title title"><%= link_to post.title, post %></h2>

                    <p class="card-text"><%= post.content %></p>
                    <p class="card-text"><%= post.limit %></p>
                    <p class="card-text"><small class="text-muted"><%= post.user.email %></small></p>
                    
                </div>
                <div class="card-footer">
                    <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(post.created_at)%> ago</small></p>

                </div>
            </div>
        </div>
    <% end %>
</div>