config/routes.rb
Rails.application.routes.draw do
  
  resources :pages
    resources :groups do
        collection do
            post 'join'
            post 'unjoin'
        end
    end
    get 'dashboard/index'
    #get 'posts/checkout'
    get 'notes/donate'
    get 'notes/accept'
    get 'home/index'
    get 'home/aboutus'
    get 'home/contact'
    get 'home/faq'
    get 'home/map'
    get 'home/privacy'
    get 'home/tos'
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :posts do
      resources :post_applications, only: [:create, :destroy]

      member do 
        patch 'accept_applicant'
        patch 'unaccept_applicant'
        get 'checkout'
        get 'accept'
        # post 'pay_teenager'
      end
    end

    get 'posts/checkout'
    get 'delete_resume' => 'pages#delete_resume'
    get 'delete_transcript' => 'pages#delete_transcript'



    root 'home#index'
    
    resource :profiles

    resources :notes
    get 'note/index'
    get 'like' => 'notes#like'
    get 'unlike' => 'notes#unlike'
    get 'dislike' => 'notes#dislike'
    get 'undislike' => 'notes#undislike'
    
    
    resources :notes do
        resources :comments
    end
    resources :users do
        resources :comments
    end
end

app/models/note.rb
class Note < ApplicationRecord
    validates :title, presence: true
    validates :course, presence: true, :case_sensitive => false
    
    belongs_to :user
    has_one :page, :through => :user
    
    has_many_attached :attachments, dependent: :delete_all
    has_many :comments, dependent: :delete_all
    
    acts_as_votable
    
    def self.search(search)
        if search
            if search == ""
                self.all
            else
                self.where("lower(course) = ?", search.downcase)
            end
        else
            self.all
        end
    end

    def accept_donation(amount)
        self.user.accept_donation_user(amount.to_f)
    end

    def self.searchEmail(search)
        if search
            if search == ""
                self.all
            else
                self.joins(:user).where("lower(Users.email) = ?", search.downcase)
            end
        else
            self.all
        end
    end

    def self.searchName(search)
        if search
            if search == ""
                self.all
            else
                self.joins(:page).where("lower(Pages.name) = ?", search.downcase)
            end
            else
                self.all
        end
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    # only signed in can create notes
    before_action :authenticate_user!, except: [:index, :show]
    before_action :require_permission, only: [:edit, :update, :destroy]
    
    
    def index
        sort_order = sort_column + " " + sort_direction
        
        @notes = Note.order(sort_order)
        
        if Note.search(params[:search])
            #@notes = Note.search(params[:search]).order("created_at DESC")
            @notes = @notes.search(params[:search])
        end
        if Note.searchEmail(params[:searchEmail])
            @notes = @notes.searchEmail(params[:searchEmail])
        end
        if Note.searchName(params[:searchName])
            @notes = @notes.searchName(params[:searchName])
        end
    end
    
    def show
        @note = Note.find(params[:id])
    end
    
    def new
        # user has_many notes
        # @note = Note.new
        @note = current_user.notes.build
    end
    
    def create
        @note = current_user.notes.build(note_params)
        
        if @note.save
            redirect_to @note
        else
            render 'new'
        end
    end
    
    def edit
        @note = find_note
    end
    
    def update
        if @note.update(note_params)
            redirect_to @note
        else
            render 'edit'
        end
    end
    
    def destroy
        @note.destroy
        redirect_to notes_url
    end

    #voting system
    def like
        @note = Note.find(params[:id])
        @note.liked_by current_user
        if @note.vote_registered? == true
            flash[:success] = "Successfully liked this note."
        else
            flash[:danger] = "You have already liked this note."
        end
        redirect_back(fallback_location: root_path)
    end
    def unlike
        @note = Note.find(params[:id])
        @note.unliked_by current_user
        if @note.vote_registered? == false
            flash[:success] = "Successfully unliked this note."
        else
            flash[:danger] = "You cannot unlike this note."
        end
        redirect_back(fallback_location: root_path)
    end

    def dislike
        @note = Note.find(params[:id])
        @note.disliked_by current_user
        if @note.vote_registered? == true
            flash[:success] = "Successfully disliked this note."
            else
            flash[:danger] = "You have already disliked this note."
        end
        redirect_back(fallback_location: root_path)
    end
    def undislike
        @note = Note.find(params[:id])
        @note.undisliked_by current_user
        if @note.vote_registered? == false
            flash[:success] = "Successfully undisliked this note."
            else
            flash[:danger] = "You cannot undislike this note."
        end
        redirect_back(fallback_location: root_path)
    end
    
    # Buy me a coffee
    def donate
        @note = Note.find(params[:noteid])
    end

    def accept
        @note = Note.find(params[:noteid])
    end

    
    private
    
    def find_note
        @note = Note.find(params[:id])
    end
    
    
    def note_params
        params.require(:note).permit(:title, :course, :prof, :content, :search, :searchName, :searchEmail, attachments: [])
    end
    
    def require_permission
        if current_user != Note.find(params[:id]).user
            redirect_to notes_url
        end
    end
    
    def sort_column
        params[:sort] || "created_at"
    end
    
    def sort_direction
        params[:direction] || "desc"
    end
end

app/helpers/notes_helper.rb
module NotesHelper
    #sorting
    def togglesort(column, title = nil)
        title = title || column.titleize
        if column == "title" || column == "course" || column == "prof"
            direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
        else
            direction = (column == params[:sort] && params[:direction] == "desc") ? "asc" : "desc"
        end
        link_to title, :sort => column, :direction => direction
    end
end

app/views/notes/accept.html.erb
<div class="col-12 text-center">
    <h2>Accept successfully</h2>
    <% @note.accept_donation(1) %>
    <%= link_to "Go Back", notes_path %>
</div>

app/views/notes/donate.html.erb
<div class="col-12 text-center">
  <h1>Donate</h1>

  <p>Enter Donation Amount</p>

  <p><select type="int" id="donate_amount" onchange="show_payment()">
  <option value=1>select_amount</option>
  <option value=1>$1</option>
  <option value=2>$2</option>
  <option value=3>$3</option>
  <option value=4>$4</option>
  <option value=5>$5</option>
  </select></p>

  <body>
    <script
      src="https://www.paypal.com/sdk/js?client-id=AR4bc1-7vGLLOMOyeoxKSx6v3qR0-dFTZxwAGoGI8Jh9mtw-f3hYe6FZNcKsrAuUGHV63r6zyjw5JXw3&currency=CAD">
    </script>

    <div id="paypal-button-container"></div>

    <script>
    function show_payment() {
      var js_price = document.getElementById("donate_amount").value
      console.log(js_price)
      paypal.Buttons({
      createOrder: function(data, actions) {
        return actions.order.create({
            purchase_units: [{
              amount: {
                value: js_price
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            //alert('Transaction completed by ' + details.payer.name.given_name);
            window.location.replace("<%= notes_accept_path(noteid: @note.id) %>")
          });
        }
      }).render('#paypal-button-container');
    }
    </script>
</div>

app/views/notes/edit.html.erb
<br>
<br>
<div class="row">

<div class="col-12 text-center dashtitle">
<h1>Edit Note</h1>

<%= form_with model: @note, local: true do |form| %>
  <p>
    <%= form.label :course %><br>
    <%= form.text_field :course %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :professor %><br>
    <%= form.text_field :prof %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :attachments %><br>
    <%= form.file_field :attachments, multiple: true %>
  </p>

  <% @note.attachments.blobs.each do |document| %>
    <p>
    <%= link_to document.filename, rails_blob_path(document, disposition: 'preview') %>
    </p>
  <% end %>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<p>
    <%= link_to 'back', :back %>
</p>

</div>
</div>

app/views/notes/index.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="row">
<div class="col-12 text-center dashtitle">
<h1>
Notes
</h1>
<button class="btn btn-light"><a><%= link_to "New Note", new_note_path%></a></button>

</div>
</div>

<div class="col-12 text-center dashtitle">

<p>

<a class="btn btn-light" data-toggle="collapse" href="#collapse" role="button" aria-expanded="false" aria-controls="collapse">
Search options:
</a>
</p>
<div class="collapse" id="collapse">
    <%= form_tag(notes_path, method: :get) do %>
    <h5>Search by course:
        <%= text_field_tag(:search, params[:search]) %>
        <%= button_tag :submit do %>
            <i class='material-icons'>search</i>
        <% end %>
    </h5>

    <h5>Search by name:&nbsp;&nbsp;
        <%= text_field_tag(:searchName, params[:searchName]) %>
        <%= button_tag :submit do %>
        <i class='material-icons'>search</i>
        <% end %>
    </h5>

    <h5>Search by email:&nbsp;&nbsp;
        <%= text_field_tag(:searchEmail, params[:searchEmail]) %>
        <%= button_tag :submit do %>
        <i class='material-icons'>search</i>
        <% end %>
    </h5>
</div>

<button class="btn btn-light"><a><%= link_to 'Clear Search', notes_url, :class => 'clearsearch' %></a></button>

</div>

<br>
<br>
<div class="row">
<div class="col-2 col-md-1"></div>
<div class="col-md-11 col-10 text-left">
<h3>Sort by:</h3>
<p>
    <th><%= togglesort "title", "Title" %></th> |
    <th><%= togglesort "course", "Course" %></th> |
    <th><%= togglesort "prof", "Professor" %></th> |
    <th><%= togglesort "created_at", "Created" %></th> | 
    <th><%= togglesort "cached_votes_score", "Likes" %></th>
</p>
<% end %>
</div>
</div>
<div  class="row" >
<% @notes.each do |note|%>
    <div class="col-md-4 col-sm-6" style="margin-top:3vh;margin-bottom:3vh;">
        <div class="card">
            
            <div class="card-body">
                <h4><%= note.course %> - <%= note.prof %></h4>
                <h2 class="title"><%= link_to note.title, note %></h2>

                <p class="card-text">By <%= link_to note.user.page.name, page_path(note.user.id), :class => 'link_to_color' %></p>
                <p class="card-text"><%= note.content %> </p>

                <p>Likes: <%= note.cached_votes_score %>
                (<% if note.cached_votes_total == 0 %><%= note.cached_votes_up.to_f * 100 %>
                <% else %><%= (note.cached_votes_up.to_f/note.cached_votes_total.to_f * 100).round(2) %>
                <% end %>%)
                </p>
                <p class="vote">
                    <%= link_to '<i class="fas fa-heart like"></i>'.html_safe,controller: "notes", action: "like", id: note.id  %>
                    <%= link_to '<i class="fas fa-thumbs-down dislike"></i>'.html_safe,controller: "notes", action: "dislike", id: note.id  %>
                </p>
                
            </div>
            <div class="card-footer">
                <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(note.created_at)%> ago</small></p>

            </div>
        </div>
    </div>
<% end %>
</div>

app/views/notes/new.html.erb
<br>
<br>
<div class="row">

<div class="col-12 text-center dashtitle">
<h1>Create New Note</h1>

<%= form_with scope: :note, url: notes_path, local: true do |form| %>
  <p>
    <%= form.label :course %><br>
    <%= form.text_field :course %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  <p>
    <%= form.label :professor %><br>
    <%= form.text_field :prof %>
</p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :attachments %><br>
    <%= form.file_field :attachments, multiple: true %>
  </p>


  <p>
    <%= form.submit %>
  </p>

  <p>
    <%= link_to 'Back', :back %>
  </p>

<% end %>
</div>
</div>

app/views/notes/show.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<br>
<div id="notes">
    <div class="row dashtitle">
    <div class="col-12 text-center">
    <h1><%= @note.title %></h1>
    </div>
    </div>
    <p class = "date">Created <%= time_ago_in_words(@note.created_at)%> ago </p>
    <p>By
    <%= link_to @note.user.page.name, page_path(@note.user.id), :class => 'link_to_color' %>
    </p>

    <div class="note">
        <h5 class = "notetitle">Course:</h5>
        <p><%= @note.course %></p>

        <h5 class = "notetitle">Professor:</h5>
        <p><%= @note.prof %></p>

        <h5 class = "notetitle">Description:</h5>
        <p><%= @note.content %></p>

        <h5 class = "notetitle">Attachments:</h5>
        <% @note.attachments.blobs.each do |document| %>
        <p>
            <%= link_to document.filename, rails_blob_path(document, disposition: 'preview'), target: :_blank, :class => 'link_to_color' %>
        </p>
        <% end %>

        <h5 class = "notetitle">Likes:</h5>
        <p>Likes: <%= @note.cached_votes_score %>
        (<% if @note.cached_votes_total == 0 %><%= @note.cached_votes_up.to_f * 100 %>
        <% else %><%= (@note.cached_votes_up.to_f/@note.cached_votes_total.to_f * 100).round(2) %>
        <% end %>%)
        </p>
    </div>

    <p>
    <%= link_to '<i class="fas fa-heart"></i>'.html_safe,controller: "notes", action: "like", id: @note.id  %>
    <%= link_to '<i class="fas fa-thumbs-down"></i>'.html_safe,controller: "notes", action: "dislike", id: @note.id  %> | 
    <%= link_to "Donate", notes_donate_path(noteid: @note.id) %>
    </p>

    <% if current_user.id == @note.user.id %>
    <%= link_to 'Edit', edit_note_path(id: @note.id)%> |
    <%= link_to 'Delete', note_path(@note), method: :delete, data: {confirm: "Are you sure you want to delete this?"}%> |
    <% end %>
    <%= link_to 'Notes', notes_url %> |
    <%= link_to 'Back', :back %>
</div>

<br/>

<div id="notes">
    <%= render "comments/show" %>
    <br/>
    <%= render "comments/comment" %>
</div>