config/routes.rb
Rails.application.routes.draw do
  
  resources :pages
    resources :groups do
        collection do
            post 'join'
            post 'unjoin'
        end
    end
    get 'dashboard/index'
    #get 'posts/checkout'
    get 'notes/donate'
    get 'notes/accept'
    get 'home/index'
    get 'home/aboutus'
    get 'home/contact'
    get 'home/faq'
    get 'home/map'
    get 'home/privacy'
    get 'home/tos'
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :posts do
      resources :post_applications, only: [:create, :destroy]

      member do 
        patch 'accept_applicant'
        patch 'unaccept_applicant'
        get 'checkout'
        get 'accept'
        # post 'pay_teenager'
      end
    end

    get 'posts/checkout'
    get 'delete_resume' => 'pages#delete_resume'
    get 'delete_transcript' => 'pages#delete_transcript'



    root 'home#index'
    
    resource :profiles

    resources :notes
    get 'note/index'
    get 'like' => 'notes#like'
    get 'unlike' => 'notes#unlike'
    get 'dislike' => 'notes#dislike'
    get 'undislike' => 'notes#undislike'
    
    
    resources :notes do
        resources :comments
    end
    resources :users do
        resources :comments
    end
end

app/models/post.rb
class Post < ApplicationRecord
    # dependant on user but not post_member
    # validates_prescence_of :user

    belongs_to :user
    has_many :post_applications, dependent: :destroy
    # belongs_to :user
    # belongs_to :post_member

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    # only signed in can create posts
    before_action :authenticate_user!, except: [:index, :show, :checkout]
    before_action :require_permission, only: [:edit, :update, :destroy]


    def index
        if params[:category].blank?
            @posts = Post.all.order("created_at DESC")
        else 
            @category_id = Category.find_by(name: params[:category]).id
            @posts = Post.where(category_id: @category_id).order("created_at DESC")
        end
    end

    def show
        @post = Post.find(params[:id])
        # data for paypal
        
        # @user = @post.user
        # @user_id = @user.id
        # @user.name  is the name
        #for now take an arbritary price like 10$
        

    end

    def new
        # user has_many posts
        # @post = Post.new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to @post
        else 
            render 'new'
        end
    end

    def edit
        @notes = Note.all.collect {|note| [ note.title, note.id ] }
    end

    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end

    def accept_applicant
        @post = find_post
        applicant_id = params[:post_application_id]
        applicant = @post.post_applications.where(id: applicant_id)
        if !applicant.empty?
            applicant.update_all(is_accepted: true)
            redirect_to post_path(@post), notice:"Accepted applicant"
        else
            redirect_back fallback_location: root_url
        end

    end

    def unaccept_applicant
        @post = find_post
        applicant_id = params[:post_application_id]
        applicant = @post.post_applications.where(id: applicant_id)
        if !applicant.empty?
            applicant.update_all(is_accepted: false)
            redirect_to post_path(@post), notice:"Unaccepted applicant"

        else
            redirect_back fallback_location: root_url
        end

    end

    def checkout
        @post = Post.find(params[:postid])
        @app_id = params[:app_id]
        @price = params[:price]
    end

    def accept
        @post = Post.find(params[:postid])
        @app_id = params[:app_id]
        @applicant = @post.post_applications.where(id: params[:app_id])[0]
        @amount = params[:amount]
    end


    private

    def find_post
        Post.find(params[:id])
    end


    def post_params
        params.require(:post).permit(:title, :content, :limit, :category_id, :is_accepting_applicants, :price)
    end
    
    def require_permission
        if current_user != Post.find(params[:id]).user
            redirect_to root_path
        end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/accept.html.erb
<div class="col-12 text-center">
    <h2>Accept successfully</h2>
    <% @applicant.accept_payment(@amount) %>
    <h4><%= link_to "Go Back", accept_applicant_post_path(@post, :post_application_id => @app_id), method: :patch %></h4>
</div>

app/views/posts/checkout.html.erb
<div class="row dashtitle">

  <div class="col-12 text-center">
    <h1>Check Out</h1>

    <% current_price = @price %>

    <h2>$ <%= current_price %></h2>


    <body>
      <script
        src="https://www.paypal.com/sdk/js?client-id=AR4bc1-7vGLLOMOyeoxKSx6v3qR0-dFTZxwAGoGI8Jh9mtw-f3hYe6FZNcKsrAuUGHV63r6zyjw5JXw3&currency=CAD">
      </script>

      <div id="paypal-button-container"></div>

      <script>
      var js_price = <%= current_price %>
      console.log(js_price)
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: js_price
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            //alert('Transaction completed by ' + details.payer.name.given_name);
            window.location.replace("<%= accept_post_path(postid: @post.id, app_id: @app_id, amount: current_price.to_f) %>")
          });
        }
      }).render('#paypal-button-container');
      </script>
    </div>
  </div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for(@post, url: {action: 'update', id: @post.id}) do |form| %>
  <p>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose A Category"} %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :number %><br>
    <%= form.number_field :limit %>
  </p> 

  <p>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "posts" , posts_path%>

app/views/posts/index.html.erb
<div class="row dashtitle">
    <div class="col-12 text-center">

        <h1>
        Jobs
        </h1>
        <button class="btn btn-light"><a><%= link_to "Create Job", new_post_path%></a></button>


    </div>

</div>


<div  class="row" >
<% @posts.each do |post|%>
    <div class="col-md-3 col-sm-6" style="margin-top:8vh;">
        <div class="card">
            
            <div class="card-body">
                
                <h2 class="card-title title"><%= link_to post.title, post %></h2>


                <p class="card-text"><%= post.content %></p>
                <p class="card-text"><%= post.limit %></p>
                <p class="card-text"><small class="text-muted"><%= post.user.email %></small></p>



            </div>
            <div class="card-footer">
                <p class="card-text"><small class="text-muted">updated <%= time_ago_in_words(post.created_at)%> ago</small></p>

            </div>
        </div>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<br>
<br>
<div class="row">
<div class="col-12 text-center dashtitle">
<h1>Create New Post</h1>

<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <p>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose A Category"} %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :number %><br>
    <%= form.number_field :limit %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: :any %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>
</div>

app/views/posts/show.html.erb
<div  class="row dashtitle" >
    <div class="col-12" style="margin-top:8vh;">
        <div class="card">
            
            <div class="card-body">
                


                <p class="card-text"><h1><%= @post.title %></p>
                <p class="card-text"><%= @post.content %></p>

                <p class="card-text">Price: <%= @post.price %></p>
                <p class="card-text"><small class="text-muted"><%= @post.user.email %></small></p>



            </div>
            <div class="card-footer">
                <p class="card-text"><small class="text-muted">updated <%= time_ago_in_words(@post.created_at)%> ago</small></p>

            </div>
        </div>
    </div>
</div>


<div class="row">
  <div class="col-12 text-center dashtitle">
    <% if current_user  == @post.user %>
      <h1 class="page_title">Applicants to this Job:</h1>
      <br>
      <br>
      <h1 class="page_title">Applicants to this Job:</h1>
      <% @apps = @post.post_applications.includes(:user)%>
      <% @apps.order("created_at DESC").each do |app| %>
        <li>
          <%= app.user.email %>
          <% if !app.is_accepted %>
            <%= link_to "Accept and pay", checkout_post_path(postid: @post.id, app_id: app.id, price: @post.price) %>
          <% else %>
            <%= link_to "Unaccept", unaccept_applicant_post_path(@post, :post_application_id => app.id), method: :patch %>
          <% end %>
        </li>
        <br>
      <% end %>


      <%= link_to 'edit', edit_post_path(@post)%>
      <%= link_to 'delete', post_path(@post), method: :delete, data: {confirm: "are you sure you want to delte this?"} %>
    <%else%>
      <% app = @post.post_applications.where(user_id: current_user.id).last %>
      <% if app.blank? %>
          <%= form_with(model: [ @post, @post.post_applications.new ], local: true) do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%= form.submit %>
          <% end %>
        
      <% else %>
          <%= button_to 'Cancel Job Application',
          post_post_application_path(@post, app),
          method: :delete,
          data: {confirm: 'Are you sure?'} %>
      <% end %>
    <%end %>
  </div>
</div>
<div class="row">
<div class="col-12 text-center dashbutton">

 <button class="btn btn-light"><a><%= link_to "home", root_path %></a></button>
 </div>
</div>