config/routes.rb
Rails.application.routes.draw do
  
  resources :pages
    resources :groups do
        collection do
            post 'join'
            post 'unjoin'
        end
    end
    get 'dashboard/index'
    #get 'posts/checkout'
    get 'notes/donate'
    get 'notes/accept'
    get 'home/index'
    get 'home/aboutus'
    get 'home/contact'
    get 'home/faq'
    get 'home/map'
    get 'home/privacy'
    get 'home/tos'
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :posts do
      resources :post_applications, only: [:create, :destroy]

      member do 
        patch 'accept_applicant'
        patch 'unaccept_applicant'
        get 'checkout'
        get 'accept'
        # post 'pay_teenager'
      end
    end

    get 'posts/checkout'
    get 'delete_resume' => 'pages#delete_resume'
    get 'delete_transcript' => 'pages#delete_transcript'



    root 'home#index'
    
    resource :profiles

    resources :notes
    get 'note/index'
    get 'like' => 'notes#like'
    get 'unlike' => 'notes#unlike'
    get 'dislike' => 'notes#dislike'
    get 'undislike' => 'notes#undislike'
    
    
    resources :notes do
        resources :comments
    end
    resources :users do
        resources :comments
    end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <title>StudyBuddy</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      
   </head>
   <body>   
      
   <%if user_signed_in? %>
      <%# start navbar %>
      <!-- Wrapper -->
      <div class="wrapper">
      
         <!-- Sidebar -->
      <nav class="sidebar">
 
        <!-- close sidebar menu -->
        <div class="dismiss">
            <i class="fas fa-arrow-left"></i>
        </div>
 
        <div class="logo">
               <h3 class="welcomePage">StudyBuddy</h3>
        </div>
 
        <ul class="list-unstyled menu-elements">

            <li>
               <%= link_to "Home", root_path, :class => "scroll-link" %></i>
            </li>
            <li>
               <%= link_to "Dashboard", dashboard_index_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Notes", notes_url, :class => "scroll-link" %>        
            </li>
            <li>
               <%= link_to "Groups", groups_url, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Buddies", pages_url,  :class => "scroll-link" %>
            </li>
            <%# accordian menus %>

            <li>
                <a href="#postsSections" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" role="button" aria-controls="otherSections">
                    Jobs
                </a>
                <ul class="collapse list-unstyled" id="postsSections">
                    <li>
                        <%= link_to "Jobs", posts_url, :class => "scroll-link" %>        
                    </li>
                     <% Category.all.each do |category| %>
                        <li>
                           <%= link_to category.name, posts_path(category: category.name), :class => "scroll-link" %>
                        </li>
                     <% end %>
                </ul>
            </li>
            <li>
                <a href="#settingsSections" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" role="button" aria-controls="otherSections">
                    Settings
                </a>
                <ul class="collapse list-unstyled" id="settingsSections">
                    <li>
                     <%= link_to "View Profile",  current_user.page , :class => "scroll-link"  %>
                    </li>
                    <li>
                     <%= link_to "My Account", edit_user_registration_path(current_user) , :class => "scroll-link" %>
                    </li>
                    <li></li>
                    <li><%= link_to "Log out #{current_user.email}", destroy_user_session_path, :method => :delete , :class => "scroll-link" %></li> 

                    
                </ul>
            </li>
            <br>
            <li>
               <%= link_to "About Us", home_aboutus_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Contact", home_contact_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Site Map", home_map_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "FAQ", home_faq_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Terms of Service", home_tos_path, :class => "scroll-link" %>
            </li>
            <li>
               <%= link_to "Privacy Policy", home_privacy_path, :class => "scroll-link" %>
            </li>
        </ul>
 
        <div class="to-top">
            <a class="btn btn-primary btn-customized-3" href="#" role="button">
                <i class="fas fa-arrow-up"></i> Top
            </a>
        </div>
 
        
 
      </nav>
         <!-- End sidebar -->
      
         
      
         <!-- Content -->
         <div class="content">
      
            <!-- open sidebar menu -->
            <a class="btn btn-primary btn-customized open-menu" href="#" role="button">
                  <i class="fas fa-align-left"></i> <!-- menu button -->
            </a>
      
            <!-- ... -->
      
            <!-- here is the page's content (not shown here) -->
      
            <!-- ... -->
      
         </div>
         <!-- End content -->
      
      </div>
   <% else %>

      <button class="btn btn-outline-success my-2 my-sm-0"><a><%= link_to "Sign Up", new_user_registration_path%></a></button>
      <button class="btn btn-outline-success my-2 my-sm-0"><a><%= link_to "Sign In", new_user_session_path%></a></button>
   <% end %>


      <%# end navbar %>
      <div class="container mx-auto" style="width: 90vw;">
         <%= yield %>
      </div>


      <script>
     
         jQuery(document).ready(function() {
 
            $('.dismiss, .overlay').on('click', function() {
               $('.sidebar').removeClass('active');
               $('.overlay').removeClass('active');
            });
         
            $('.open-menu').on('click', function(e) {
               e.preventDefault();
               $('.sidebar').addClass('active');
               $('.overlay').addClass('active');
               // close opened sub-menus
               $('.collapse.show').toggleClass('show');
               $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
 
   
                     
          /*  Navigation */
         
            
            
            function scroll_to(clicked_link, nav_height) {
               var element_class = clicked_link.attr('href').replace('#', '.');
               var scroll_to = 0;
               if(element_class != '.top-content') {
                  element_class += '-container';
                  scroll_to = $(element_class).offset().top - nav_height;
               }
               if($(window).scrollTop() != scroll_to) {
                  $('html, body').stop().animate({scrollTop: scroll_to}, 1000);
               }
            }
            $('.to-top a').on('click', function(e) {
               e.preventDefault();
               if($(window).scrollTop() != 0) {
                  $('html, body').stop().animate({scrollTop: 0}, 1000);
               }
            });
            
            
 
         });
    
      </script>
     
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"></script>
  </body>
</html>

app/views/layouts/no_navbar.html.erb
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   </head>
   <body>
      <div class="container">
         <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
      </div>
      <div class="container">
         <%= yield %>
      </div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   </body>
</html>